import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import CourseContextLayout from "./Candidate/context/CourseContextLayout";
import { AnswerProvider } from "./Candidate/context/AnswerContextLayout";
import { CorrectnessProvider } from "./Candidate/context/CorrectContextLayout";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CourseContextLayout>
          <AnswerProvider>
            <CorrectnessProvider>{children}</CorrectnessProvider>
          </AnswerProvider>
        </CourseContextLayout>
      </body>
    </html>
  );
}
